[CRIP-4] - Integrar Swagger al proyecto
matiasnfuentes/criptop2p pull request #2
Opened 2022-09-02 18:03 UTC by matiasnfuentes

Este PR resuelve [CRIP-4](https://criptop2p.atlassian.net/browse/CRIP-4)

Integra open api v3 y swagger al proyecto. Las dependencias de spring security fueron comentadas para que no pida loguearse al acceder a las rutas. Por el momento no son necesarias, mas adelante las configuraremos bien.

Se puede acceder a la documentación desde:

- http://localhost:8080/api-docs (JSON plano)
- http://localhost:8080/swagger-ui.html (Swagger UI)

2022-09-03 14:20 UTC, DanielBarbe commented on build.gradle.kts
>  	providedRuntime("org.springframework.boot:spring-boot-starter-tomcat")
En mi caso, esta linea tuve que comentarla porque se me cerraba la app. Aparentemente hay conflictos entre el spring-boot-starter-tomcat y "spring-boot-starter-web".

2022-09-03 14:21 UTC, DanielBarbe requested changes
Habria que comentar la linea 29, `providedRuntime("org.springframework.boot:spring-boot-starter-tomcat")`

2022-09-03 14:30 UTC, matiasnfuentes commented on build.gradle.kts
>  	providedRuntime("org.springframework.boot:spring-boot-starter-tomcat")
MM eso es raro, que error te tira ? A mi me está funcionando joya

2022-09-03 15:02 UTC, DanielBarbe commented on build.gradle.kts
>  	providedRuntime("org.springframework.boot:spring-boot-starter-tomcat")
No estoy seguro, pero se me cierra la app sola.

```
2022-09-03 11:59:55.635  INFO 6247 --- [  restartedMain] a.e.u.criptop2p.Criptop2pApplicationKt   : Started Criptop2pApplicationKt in 2.708 seconds (JVM running for 3.628)
2022-09-03 11:59:55.646  INFO 6247 --- [ionShutdownHook] j.LocalContainerEntityManagerFactoryBean : Closing JPA EntityManagerFactory for persistence unit 'default'
2022-09-03 11:59:55.646  INFO 6247 --- [ionShutdownHook] .SchemaDropperImpl$DelayedDropActionImpl : HHH000477: Starting delayed evictData of schema as part of SessionFactory shut-down'
2022-09-03 11:59:55.856  WARN 6247 --- [ionShutdownHook] o.s.b.f.support.DisposableBeanAdapter    : Invocation of destroy method failed on bean with name 'inMemoryDatabaseShutdownExecutor': org.h2.jdbc.JdbcSQLNonTransientConnectionException: La base de datos ya esta cerrada (para des-habilitar el cerrado automatico durante el shutdown de la VM, agregue ";DB_CLOSE_ON_EXIT=FALSE" a la URL de conexión)
Database is already closed (to disable automatic closing at VM shutdown, add ";DB_CLOSE_ON_EXIT=FALSE" to the db URL) [90121-214]
2022-09-03 11:59:55.856  INFO 6247 --- [ionShutdownHook] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Shutdown initiated...
2022-09-03 11:59:55.860  INFO 6247 --- [ionShutdownHook] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Shutdown completed.
```

2022-09-06 22:50 UTC, DanielBarbe approved these changes
Se ve bien.

2022-09-06 22:59 UTC, merged

2022-09-06 23:33 UTC, DanielBarbe commented on build.gradle.kts
>  	providedRuntime("org.springframework.boot:spring-boot-starter-tomcat")
Encontre que hay lo estaba ejecutando mal desde intellij:
`Gradle tab > Tasks > application > bootRun`
Mala mia. ✋